apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-dbdump
  namespace: <NAMESPACE>
data:
  dump.sh: |-
    #!/bin/bash

    DATE=$(date +%Y-%m-%d-%H.%M.%S)
    mysqldump -h <DB_HOSTNAME> -u $DATABASE_USER <DATABASE> | gzip > <DATABASE>_$DATE.sql.gz

    ### EXTRA ACTIONS ###

    ## AWS: Upload to S3 Bucket
    ## Include AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in secrets.
    # > aws s3 cp <DATABASE>_$DATE.sql.gz s3://<BUCKET>/<PATH>

    ## AZURE: Upload to Blob Storage
    ## Include AZURE_STORAGE_CONNECTION_STRING in secrets.
    # > az storage blob upload -f <DATABASE>_$DATE.sql.gz -c uax-db-dumps -n <DATABASE>_$DATE.sql.gz --connection-string $AZURE_STORAGE_CONNECTION_STRING